// Regenerate the committed contract specs from the approved v2 WASM bundle.
//
//   node scripts/contract-specs.mjs generate   # write
//   node scripts/contract-specs.mjs check      # fail on drift (CI)
//
// A contract's spec is a custom section inside its own WASM, so it is read
// straight out of the artifact via `Spec.fromWasm`. That needs no Stellar CLI,
// no temp dirs, and no TypeScript AST parsing — this script only moves bytes.
//
// Provenance is deliberately NOT checked here. The source commit, source tree,
// Cargo.lock digest, toolchain versions, per-WASM SHA-256, and the
// class-consumes-its-generated-spec rule are all asserted by
// test/spec_consistency.test.ts against the manifest this script copies into
// test/fixtures/specs/wasm-manifest.json. Assertions belong in the suite that
// reports them, not in the generator: the old in-script copy duplicated the
// test exactly, and because it ran first it could only ever fail with a worse
// message than the test it shadowed.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { contract } from '@stellar/stellar-sdk';

const sdkRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
// The approved contracts worktree. A bare absolute path here silently rotted
// once already: the checkout moved, every run died on ENOENT, and the drift
// this script exists to surface went unnoticed for two contract releases. The
// sibling default tracks the standard workspace layout; ZENEX_CONTRACTS_ROOT
// covers everything else.
const contractsRoot = resolve(
    process.env.ZENEX_CONTRACTS_ROOT ?? resolve(sdkRoot, '../zenex-contracts'),
);
const manifestPath = resolve(contractsRoot, 'artifacts/v2/manifest.json');

// Keyed by artifact stem (also the fixture filename); the manifest spells the
// same packages with hyphens. Order fixes the layout of the generated module.
const CONTRACTS = [
    ['trading', 'tradingSpec'],
    ['trading_router', 'tradingRouterSpec'],
    ['factory', 'factorySpec'],
    ['strategy_vault', 'strategyVaultSpec'],
    ['oracle', 'oracleSpec'],
    ['treasury', 'treasurySpec'],
    ['governance', 'governanceSpec'],
];

function fail(message) {
    throw new Error(`Contract spec generation failed: ${message}`);
}

/** Resolve a manifest-declared artifact path, refusing to leave the worktree. */
function artifactPath(declared) {
    const path = resolve(contractsRoot, declared);
    if (relative(contractsRoot, path).startsWith('..')) {
        fail(`artifact path leaves the contracts worktree: ${declared}`);
    }
    if (!existsSync(path)) fail(`artifact is missing at ${declared}`);
    return path;
}

async function specEntries(wasmPath) {
    const spec = await contract.Spec.fromWasm(readFileSync(wasmPath));
    return spec.entries.map((entry) => entry.toXDR('base64'));
}

function renderGeneratedModule(generated) {
    const lines = [
        '// Generated by scripts/contract-specs.mjs from the approved WASM manifest.',
        '// Do not edit these base64 XDR arrays by hand.',
        '',
    ];

    for (const [key, exportName] of CONTRACTS) {
        lines.push(`export const ${exportName}: string[] = [`);
        for (const entry of generated.get(key)) lines.push(`    '${entry}',`);
        lines.push('];', '');
    }

    return `${lines.join('\n').trimEnd()}\n`;
}

function writeOrCheck(path, expected, mode) {
    const bytes = Buffer.isBuffer(expected) ? expected : Buffer.from(expected);
    if (mode === 'generate') {
        mkdirSync(dirname(path), { recursive: true });
        writeFileSync(path, bytes);
        return;
    }
    if (!existsSync(path) || !readFileSync(path).equals(bytes)) {
        fail(
            `${relative(sdkRoot, path)} is out of date. `
            + 'Run `npm run specs:generate` and commit the result.',
        );
    }
}

async function run(mode) {
    if (mode !== 'generate' && mode !== 'check') {
        throw new Error('Usage: node scripts/contract-specs.mjs <generate|check>');
    }
    if (!existsSync(manifestPath)) {
        fail(
            `no artifact manifest at ${manifestPath}. Build it with \`make build\` in the `
            + 'contracts worktree and regenerate artifacts/v2/, or point ZENEX_CONTRACTS_ROOT '
            + 'at the approved checkout.',
        );
    }

    const manifestBytes = readFileSync(manifestPath);
    const manifest = JSON.parse(manifestBytes.toString('utf8'));

    const generated = new Map();
    for (const [key] of CONTRACTS) {
        const pkg = key.replaceAll('_', '-');
        const entry = manifest.contracts?.find((candidate) => candidate.package === pkg);
        if (!entry) fail(`manifest is missing ${pkg}`);
        generated.set(key, await specEntries(artifactPath(entry.path)));
    }

    writeOrCheck(resolve(sdkRoot, 'src/contracts/contract_specs.ts'), renderGeneratedModule(generated), mode);
    writeOrCheck(resolve(sdkRoot, 'test/fixtures/specs/wasm-manifest.json'), manifestBytes, mode);
    for (const [key] of CONTRACTS) {
        const fixture = `${JSON.stringify(generated.get(key), null, 4)}\n`;
        writeOrCheck(resolve(sdkRoot, `test/fixtures/specs/${key}.json`), fixture, mode);
    }

    process.stdout.write(
        `Core contract specs ${mode === 'generate' ? 'generated' : 'verified'} from ${manifest.contractsCommit}.\n`,
    );
}

try {
    await run(process.argv[2]);
} catch (error) {
    process.stderr.write(`${error.message}\n`);
    process.exitCode = 1;
}
