// Regenerate the committed contract specs from the contracts build output.
//
//   node scripts/contract-specs.mjs generate   # write
//   node scripts/contract-specs.mjs check      # fail on drift
//
// Specs are read straight out of `target/wasm32v1-none/release/*.wasm` in the
// contracts worktree — the freshest local build, so there is no artifact
// bundle to fall out of date and no rebuild-then-republish step between
// changing a contract and picking the change up here. Run `make build` in the
// contracts worktree first; that is the only prerequisite.
//
// A contract's spec is a custom section inside its own WASM, so `Spec.fromWasm`
// reads it directly: no Stellar CLI, no temp dirs, no TypeScript AST parsing.
//
// This script does not verify provenance. It does not pin a source commit, a
// toolchain, or per-WASM hashes, and it reads whatever was last built rather
// than an approved bundle — including uncommitted contract edits, which is the
// point. Deployment provenance is enforced where it belongs: zenex-infra
// re-verifies every artifact hash against zenex-contracts/artifacts/v2/ on the
// deploy path. Nothing here feeds that path.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { contract } from '@stellar/stellar-sdk';

const sdkRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
// The contracts worktree. A bare absolute path here silently rotted once
// already: the checkout moved and every run died on ENOENT. The sibling
// default tracks the standard workspace layout; ZENEX_CONTRACTS_ROOT covers
// everything else.
const contractsRoot = resolve(
    process.env.ZENEX_CONTRACTS_ROOT ?? resolve(sdkRoot, '../zenex-contracts'),
);
const wasmDir = resolve(contractsRoot, 'target/wasm32v1-none/release');

// Keyed by WASM stem (also the fixture filename). Order fixes the layout of
// the generated module.
const CONTRACTS = [
    ['market', 'marketSpec'],
    ['market_router', 'marketRouterSpec'],
    ['factory', 'factorySpec'],
    ['strategy_vault', 'strategyVaultSpec'],
    ['oracle', 'oracleSpec'],
    ['treasury', 'treasurySpec'],
    ['governance', 'governanceSpec'],
];

function fail(message) {
    throw new Error(`Contract spec generation failed: ${message}`);
}

async function specEntries(stem) {
    const wasmPath = resolve(wasmDir, `${stem}.wasm`);
    if (!existsSync(wasmPath)) {
        fail(
            `no build output for ${stem} at ${wasmPath}. Run \`make build\` in the contracts `
            + 'worktree, or point ZENEX_CONTRACTS_ROOT at it.',
        );
    }
    const spec = await contract.Spec.fromWasm(readFileSync(wasmPath));
    return spec.entries.map((entry) => entry.toXDR('base64'));
}

function renderGeneratedModule(generated) {
    const lines = [
        '// Generated by scripts/contract-specs.mjs from the contracts build output.',
        '// Do not edit these base64 XDR arrays by hand.',
        '',
    ];

    for (const [stem, exportName] of CONTRACTS) {
        lines.push(`export const ${exportName}: string[] = [`);
        for (const entry of generated.get(stem)) lines.push(`    '${entry}',`);
        lines.push('];', '');
    }

    return `${lines.join('\n').trimEnd()}\n`;
}

function writeOrCheck(path, expected, mode) {
    const bytes = Buffer.from(expected);
    if (mode === 'generate') {
        mkdirSync(dirname(path), { recursive: true });
        writeFileSync(path, bytes);
        return;
    }
    if (!existsSync(path) || !readFileSync(path).equals(bytes)) {
        fail(
            `${relative(sdkRoot, path)} is out of date. `
            + 'Run `npm run specs:generate` and commit the result.',
        );
    }
}

async function run(mode) {
    if (mode !== 'generate' && mode !== 'check') {
        throw new Error('Usage: node scripts/contract-specs.mjs <generate|check>');
    }

    const generated = new Map();
    for (const [stem] of CONTRACTS) generated.set(stem, await specEntries(stem));

    writeOrCheck(
        resolve(sdkRoot, 'src/contracts/contract_specs.ts'),
        renderGeneratedModule(generated),
        mode,
    );
    for (const [stem] of CONTRACTS) {
        writeOrCheck(
            resolve(sdkRoot, `test/fixtures/specs/${stem}.json`),
            `${JSON.stringify(generated.get(stem), null, 4)}\n`,
            mode,
        );
    }

    process.stdout.write(
        `Core contract specs ${mode === 'generate' ? 'generated' : 'verified'} from ${relative(sdkRoot, wasmDir)}.\n`,
    );
}

try {
    await run(process.argv[2]);
} catch (error) {
    process.stderr.write(`${error.message}\n`);
    process.exitCode = 1;
}
